openapi: 3.0.0
info:
  title: Cleanup Policy API
  description: API for managing cleanup policies in Artifactory.
  version: 1.0.0
servers:
  - url: http://{host}:{port}/artifactory/api
security:
  - basicAuth: []
paths:
  /cleanup/policies:
    post:
      summary: Create or Update a Cleanup Policy
      operationId: createOrUpdateCleanupPolicy
      security:
        - basicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                key:
                  type: string
                  description: Unique identifier for the cleanup policy.
                description:
                  type: string
                  description: Description of the policy.
                cronExp:
                  type: string
                  description: Cron expression defining when the policy should run.
                itemType:
                  type: string
                  enum: [releaseBundle]
                  description: Type of item to be cleaned up by this policy.
                durationInMinutes:
                  type: integer
                  description: Duration in minutes for the policy.
                enabled:
                  type: boolean
                  description: Indicates whether the policy is enabled.
                searchCriteria:
                  type: object
                  properties:
                    includeAllProjects:
                      type: boolean
                      description: Whether the policy applies to all projects.
                    includedProjects:
                      type: array
                      items:
                        type: string
                      description: List of specific project keys for the policy.
                    releaseBundles:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            description: Name of the release bundle.
                          projectKey:
                            type: string
                            description: Project key associated with the release bundle.
                    excludePromotedEnvironments:
                      type: array
                      items:
                        type: string
                      description: Environments to be excluded from the cleanup policy.
                    createdBeforeInMonths:
                      type: integer
                      description: Age of release bundles in months for cleanup criteria.
              required: [key, itemType, durationInMinutes, enabled, searchCriteria]
      responses:
        '200':
          description: Cleanup policy created or updated successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Cleanup policy created/updated successfully."
                  policy:
                    type: object
                    $ref: '#/components/schemas/CleanupPolicy'
        '400':
          description: Invalid input.
        '500':
          description: Internal server error.
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    CleanupPolicy:
      type: object
      properties:
        key:
          type: string
          description: Unique identifier for the cleanup policy.
        description:
          type: string
          description: Description of the policy.
        cronExp:
          type: string
          description: Cron expression for scheduling the policy.
        itemType:
          type: string
          enum: [releaseBundle]
          description: Type of item to be cleaned up.
        durationInMinutes:
          type: integer
          description: Duration of the policy in minutes.
        enabled:
          type: boolean
          description: Indicates if the policy is enabled.
        searchCriteria:
          type: object
          properties:
            includeAllProjects:
              type: boolean
              description: Whether to include all projects.
            includedProjects:
              type: array
              items:
                type: string
            releaseBundles:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  projectKey:
                    type: string
            excludePromotedEnvironments:
              type: array
              items:
                type: string
            createdBeforeInMonths:
              type: integer
