openapi: 3.0.3
info:
  title: JFrog Cleanup Policies API
  description: API for managing cleanup policies in JFrog Artifactory.
  version: 1.0.0
servers:
  - url: https://your-jfrog-instance.com/artifactory/api
paths:
  /cleanup/policies:
    get:
      summary: Get a list of cleanup policies
      responses:
        '200':
          description: A list of cleanup policies
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      description: The name of the cleanup policy
                    description:
                      type: string
                      description: The description of the cleanup policy
                    last_updated:
                      type: string
                      format: date-time
                      description: The last time the cleanup policy was updated

    post:
      summary: Create a new cleanup policy
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the cleanup policy
                description:
                  type: string
                  description: The description of the cleanup policy
                criteria:
                  type: object
                  description: The criteria for the cleanup policy
                  properties:
                    type:
                      type: string
                      description: The type of criteria (e.g., "age", "size")
                    value:
                      type: string
                      description: The value associated with the criteria
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request

  /cleanup/policies/{policyName}:
    get:
      summary: Get a specific cleanup policy by name
      parameters:
        - in: path
          name: policyName
          required: true
          schema:
            type: string
          description: The name of the cleanup policy
      responses:
        '200':
          description: Details of the cleanup policy
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  description:
                    type: string
                  criteria:
                    type: object
                    properties:
                      type:
                        type: string
                      value:
                        type: string
        '404':
          description: Policy not found

    delete:
      summary: Delete a cleanup policy
      parameters:
        - in: path
          name: policyName
          required: true
          schema:
            type: string
          description: The name of the cleanup policy
      responses:
        '204':
          description: Deleted successfully
        '404':
          description: Policy not found

    put:
      summary: Update a cleanup policy
      parameters:
        - in: path
          name: policyName
          required: true
          schema:
            type: string
          description: The name of the cleanup policy
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                  description: The new description of the cleanup policy
                criteria:
                  type: object
                  description: The updated criteria for the cleanup policy
                  properties:
                    type:
                      type: string
                    value:
                      type: string
      responses:
        '200':
          description: Updated successfully
        '404':
          description: Policy not found
        '400':
          description: Bad Request

components:
  schemas:
    CleanupPolicy:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        criteria:
          type: object
          properties:
            type:
              type: string
            value:
              type: string
